import {createSlice} from '@reduxjs/toolkit';

const initialState = {
    theme: 'dark', // default theme is light
};

const themeSlice = createSlice({
    name: 'theme',
    initialState,
    reducers: {
        toggleTheme: (state) => { // toggleTheme is a reducer function that toggles the theme
            state.theme = state.theme === 'light' ? 'dark' : 'light';
        },
        }
});

export const {toggleTheme} = themeSlice.actions; // . This object contains all the action creators generated by the slice

export default themeSlice.reducer;